hosts/urls.py
from django.conf.urls import patterns, url
from hosts import views

urlpatterns = patterns('',
    url(r'^host/(?P<id>[0-9]+)$', 'hosts.views.host', name="host"),
    url(r'^dismiss/(?P<id>[0-9]+)$', 'hosts.views.dismiss_host', name="dismiss_host"),
    url(r'^reinstate/(?P<id>[0-9]+)$', 'hosts.views.reinstate_host', name="reinstate_host"),
    url(r'^create/$', 'hosts.views.create_host', name="create_host"),
    # The id in add_scrapbook url is the HOST id
    url(r'^add_scrapbook/(?P<id>[0-9]+)$', 'hosts.views.add_scrapbook', name="add_host_scrapbook"),
    url(r'^host/(?P<pk>[0-9]+)/drop$', views.DropHost.as_view(), name="drop_host"),
)

octomon/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from . import views as v

urlpatterns = patterns('',
    url(r'^$', 'octomon.views.home', name="home"),
    url(r'^login/$', 'octomon.views.octomon_login', name="login"),
    url(r'^logout/$', 'octomon.views.octomon_logout', name="logout"),
    url(r'^locationmap/$', v.LocationMap.as_view(), name="locationmap"),
    url(r'^user/(?P<id>[0-9]+)$', 'octomon.views.review_user', name="review_user"),
    url(r'^schools/', include('schools.urls')),
    url(r'^hosts/', include('hosts.urls')),
    url(r'^upload/', include('upload.urls')),
    url(r'^problems/', include('problems.urls')),
    url(r'^statistics/', include('stats.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
)

hosts/models.py
# coding: utf-8
import datetime
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


class Computer(models.Model):
    school = models.ForeignKey('schools.School', related_name='computers',
            verbose_name=_('School'))
    hostname = models.CharField(max_length=200, blank=True,
            verbose_name=_('Hostname (FQDN)'))
    serial_number = models.CharField(max_length=200, blank=True,
            verbose_name=_('Serial Number'))
    video_serial_number = models.CharField(max_length=200, blank=True,
            verbose_name=_('Video Serial Number'))
    location = models.CharField(max_length=200, blank=True,
            verbose_name=_('Location'))
    warranty_expire = models.DateField(null=True, blank=True,
            verbose_name=_('Warranty expires on'))
    # ./manage.py inspectdb gave a models.IntegerField(null=True, blank=True)
    # MySQL has a TINYINT(4). Django stores BooleanFields as TINYINT when the
    # DB doesn't have a BOOLEAN type (like MySQL). For now I use a BooleanField
    # with default=False, which seems plausible.
    dismissed = models.BooleanField(default=False)

    class Meta:
        db_table = 'computer'
        ordering = ('school', 'hostname', )

    def has_problems(self):
        return True if self.get_non_acked_alarms() else False

    def get_all_alarms(self):
        return list(self.alarms.all())

    def get_acked_alarms(self):
        return list(self.alarms.filter(ack=True))

    def get_non_acked_alarms(self):
        return list(self.alarms.filter(ack=False))

    def get_all_tickets(self):
        return list(self.tickets.all())

    def get_open_tickets(self):
        return list(self.tickets.filter(is_open=True))

    def get_closed_tickets(self):
        return list(self.tickets.filter(is_open=False))

    @property
    def last_used(self):
        usage = Use.objects.filter(host=self)
        if usage.count() > 0:
            return usage[0].timestamp
        else:
            return datetime.datetime.now().replace(hour=0, minute=0, second=0)

    @property
    def usage_count(self):
        return Use.objects.filter(host=self).count()

    def get_last_components(self):
        found_components = {}
        for x in self.components.all():
            if x.name not in found_components.keys():
                found_components[x.name] = x
            else:
                if x.timestamp > found_components[x.name].timestamp:
                    found_components[x.name] = x
        items = found_components.values()
        items.sort(cmp=lambda x,y: cmp(x.name, y.name))
        return items

    def get_daily_uses(self):
        data = {}
        for use in self.uses.all():
            day = use.timestamp.date()
            try:
                data[day] += 1
            except:
                data[day] = 1
        return data

    def get_days_of_use(self):
        data = {}
        for use in self.uses.all():
            day = use.timestamp.date()
            data[day] = 1
        return data

    def is_server(self):
        try:
            q = self.components.filter(name="is_server")
            if len(q) > 0:
                return q.order_by("-timestamp")[0].value == "yes"
            raise
        except:
            pass
        return False

    def __unicode__(self):
        return "%s - %s" % (self.school.name, self.hostname)


class Component(models.Model):
    name = models.CharField(max_length=200, blank=True, default='')
    value = models.CharField(max_length=200, blank=True, default='')
    host = models.ForeignKey('Computer', related_name='components', null=True, blank=True, default=None)
    timestamp = models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)

    class Meta:
        db_table = 'components'

    def __unicode__(self):
        return "%s - %s" % (self.host, self.name)


class HostScrapBook(models.Model):
    host = models.ForeignKey('Computer', related_name='scrapbooks')
    user = models.ForeignKey(User, related_name='host_scrapbooks')
    content = models.CharField(max_length=2000)
    timestamp = models.DateTimeField(default=datetime.datetime.now, null=True, blank=True)

    class Meta:
        db_table = 'host_scrap_book'
        ordering = ('host', '-timestamp', )

    def __unicode__(self):
        return "%s - %s" % (self.host.hostname, self.timestamp)


class Use(models.Model):
    host = models.ForeignKey('Computer', related_name='uses')
    timestamp = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'used'
        ordering = ('-timestamp',)

class UseNotGood(models.Model):
    host = models.ForeignKey('Computer', related_name='uses_not_good')
    timestamp = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'used_not_good'
        verbose_name_plural = 'uses not good'

problems/models.py
# coding: utf-8
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Alarm(models.Model):
    host = models.ForeignKey('hosts.Computer', related_name='alarms')
    definition = models.ForeignKey('AlarmDefinition', related_name='alarms', blank=True)
    description = models.CharField(max_length=200)
    timestamp = models.DateTimeField(default=datetime.now, null=True, blank=True)
    ack = models.BooleanField(default=False)
    ack_by = models.ForeignKey(User, related_name='acked_alarms', null=True, blank=True)
    ack_when = models.DateTimeField(default=None, null=True, blank=True)

    def __str__(self):
        return "%s %s %s" %(self.description, _("on"), self.host)

    class Meta:
        db_table = 'alarms'


@python_2_unicode_compatible
class AlarmDefinition(models.Model):
    user = models.ForeignKey(User, related_name='alarm_definitions')
    description = models.CharField(max_length=200)
    code = models.TextField(help_text=_("c is a Computer object"))
    active = models.BooleanField(default=False)
    local = models.BooleanField(default=True)

    def __str__(self):
        return self.description

    class Meta:
        db_table = 'alarm_definition'


@python_2_unicode_compatible
class AlarmDefinitionRun(models.Model):
    school = models.ForeignKey('schools.School', related_name='alarm_definition_runs')
    definition = models.ForeignKey('AlarmDefinition', related_name='runs')
    school_timestamp = models.FloatField(default=0, null=True, blank=True)

    def __str__(self):
        return "%s %s %s" %(self.definition, _("execution on"), self.school)

    class Meta:
        db_table = 'alarm_definition_run'


@python_2_unicode_compatible
class Ticket(models.Model):
    opened = models.DateTimeField(null=True, blank=True)
    opened_by = models.ForeignKey(User, related_name='tickets_opened')
    ticket_for = models.CharField(max_length=200, blank=True)
    object_id = models.IntegerField(null=True, blank=True)
    description = models.CharField(max_length=2000,
        verbose_name=_('Problem description'))
    closed = models.DateTimeField(default=None, null=True, blank=True)
    closed_by = models.ForeignKey(User, related_name='tickets_closed', null=True, blank=True)

    def __str__(self):
        return self.ticket_for

    class Meta:
        db_table = 'ticket'
        ordering = ('-closed', '-opened', )

    def get_duration(self):
        if self.closed:
            return self.closed - self.opened
        else:
            return 0

    @property
    def is_open(self):
        return False if self.closed else True

    @property
    def is_closed(self):
        return True if self.closed else False


@python_2_unicode_compatible
class TicketNote(models.Model):
    ticket = models.ForeignKey('Ticket', related_name='notes', null=True, blank=True)
    user = models.ForeignKey(User, related_name='ticket_notes')
    timestamp = models.DateTimeField(null=True, blank=True)
    content = models.CharField(max_length=2000, blank=True)

    def __str__(self):
        return "%s %s" %(self.ticket, _("comment"))

    class Meta:
        db_table = 'ticket_note'

hosts/forms.py
# coding: utf-8
from django import forms
import hosts.models as hmodels


class ComputerForm(forms.ModelForm):
    class Meta:
        model = hmodels.Computer
        fields = (
            'school', 'hostname', 'location',
            'serial_number', 'video_serial_number', 'warranty_expire',
        )


class HostScrapBookForm(forms.ModelForm):
    class Meta:
        model = hmodels.HostScrapBook
        fields = (
            'content', 'user', 'host',
        )
        widgets = {
            'content': forms.Textarea(attrs={'cols': 50, 'rows': 7}),
            'user': forms.HiddenInput(),
            'host': forms.HiddenInput(),
        }

hosts/views.py
# coding: utf-8
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic.edit import DeleteView
import hosts.models as hmodels
import problems.models as pmodels
import hosts.forms as hforms
import problems.forms as pforms
from hosts import utils
from octomon.mixins import UserMixin


GATHERED_PACKAGES = [
    "fuss-server",
    "fussclient",
    "octofuss-client",
    "octomon-sender",
    "octofussd",
    "octonet"
]


@login_required
def host(request, id):
    host = get_object_or_404(hmodels.Computer, pk=int(id))
    alarmformset = pforms.AlarmFormSet(
        queryset=pmodels.Alarm.objects.filter(host=host, ack=False)
    )
    scrapbookform_initial = {
        'host': host.id,
        'user_id': request.user.id,
    }
    scrapbookform = hforms.HostScrapBookForm(prefix='scrapbookform', initial=scrapbookform_initial)
    if request.method == 'POST' and 'submit_edit_host' in request.POST:
        if not request.user.has_perm('hosts.change_computer'):
            messages.error(request, _("You don't have the permissions to modify this computer"))
            return HttpResponseRedirect(reverse('host', args=[host.id,]))
        # Save the modified computer
        edit_host_form = hforms.ComputerForm(request.POST, instance=host)
        if edit_host_form.is_valid():
            saved_host = edit_host_form.save()
            return redirect('host', id=saved_host.id)
        else:
            # Form not valid
            messages.error(request, _('Computer not saved, form not valid.'))
            return redirect('host', id=id)
    edit_host_form = hforms.ComputerForm(instance=host)
    components = host.get_last_components()
    ctx = {
        'host': host,
        'edit_host_form': edit_host_form,
        'alarmformset': alarmformset,
        'scrapbookform': scrapbookform,
        'disks': utils.parse_disks(components),
        'versions': utils.filter_by_list(components, GATHERED_PACKAGES),
        'interfaces': utils.parse_interfaces(components),
        'lc_wan_mac': utils.parse_wan_mac(components),
        'etc': utils.parse_etc(components)
    }
    for i in components:
        ctx["lc_"+i.name] = i
    return render(request, 'hosts/host.html', ctx)

@login_required
def create_host(request):
    if not request.user.has_perm('hosts.add_computer'):
        messages.error(request, _("You don't have the permission to create a host"))
        return redirect('schools')
    if request.method == 'POST':
        form = hforms.ComputerForm(request.POST)
        if form.is_valid():
            host = form.save()
            messages.info(request, _('Computer %s created successfully' % host.hostname))
            return redirect('schools')
        else:
            messages.error(request, _('Computer not created, form not valid.'))
    else:
        form = hforms.ComputerForm()
        # Filter schools if the user is not superuser
        if not request.user.is_superuser:
            form.fields['school'].queryset = request.user.schools.all()
    return render(request, 'hosts/create_host.html', {
        'form': form,
    })


@login_required
def dismiss_host(request, id):
    host = get_object_or_404(hmodels.Computer, pk=int(id))
    if not request.user.has_perm('hosts.change_computer'):
        messages.error(request, _("You don't have the permission to modify a host"))
        return HttpResponseRedirect(reverse('host', args=[id,]))
    host.dismissed = True
    host.save()
    messages.info(request, _("Host dismissed successfully"))
    return HttpResponseRedirect(reverse('host', args=[host.id,]))


@login_required
def reinstate_host(request, id):
    host = get_object_or_404(hmodels.Computer, pk=int(id))
    if not request.user.has_perm('hosts.change_computer'):
        messages.error(request, _("You don't have the permission to modify a host"))
        return HttpResponseRedirect(reverse('host', args=[id,]))
    host.dismissed = False
    host.save()
    messages.info(request, _("Host reinstated successfully"))
    return HttpResponseRedirect(reverse('host', args=[host.id,]))


class DropHost(UserMixin, SuccessMessageMixin, DeleteView):
    model = hmodels.Computer
    template_name = "hosts/drop_host.html"
    success_message = _("%(hostname)s has been successfully deleted.")

    def get_success_url(self):
        return reverse_lazy("school_detail", kwargs={"pk": self.object.school.pk})


@login_required
def add_scrapbook(request, id):
    # id is the host id
    host = get_object_or_404(hmodels.Computer, pk=int(id))
    if not request.user.has_perm('hosts.add_hostscrapbook'):
        messages.error(request, _("You don't have the permissions to add a scrapbook"))
        return HttpResponseRedirect(reverse('host', args=[host.id,]))
    scrapbookform = hforms.HostScrapBookForm(request.POST, prefix='scrapbookform')
    if scrapbookform.is_valid():
        print "GOOD"
        scrapbook = scrapbookform.save()
    else:
        print "ERROR"
        print scrapbookform.data
        print scrapbookform.errors
        return HttpResponseRedirect(reverse('host', args=[host.id,]))
    return HttpResponseRedirect(reverse('host', args=[scrapbook.host.id,]))

hosts/templates/hosts/create_host.html
{% extends "base.html" %}
{% load i18n %}


{% block title %}{% trans "New Computer" %}{% endblock title %}

{% block head_resources %}
<link href="{{STATIC_URL}}css/jquery-ui.css" rel="stylesheet"/>
<script src="{{STATIC_URL}}js/jquery-ui.min.js"></script>
<script type="text/javascript">
  $(function() {
    $("#id_warranty_expire").datepicker({
      dateFormat: "yy-mm-dd",
    });
  });
</script>
{% endblock head_resources %}

{% block content %}
    <div class="span6">
      <h1>{% trans 'Add new computer' %}</h1>
      <form method="POST" action="{{ request.get_full_path }}">{% csrf_token %}
        <table class="table table-striped">
          {{form.as_table}}
        </table>
        <input class="btn" type="submit" value="{% trans 'Submit Query' %}" />
      </form>
    </div>
{% endblock content %}

hosts/templates/hosts/drop_host.html
{% extends "base.html" %}
{% load i18n static %}


{% block title %}{% trans "Dropping" %} {{object.hostname}}{% endblock %}

{% block content %}

<h1>
{% trans "Really delete" %} {{object.hostname}} ?
</h1>

{% trans "This action won't simply dismiss it, but it rather will completly drop" %}
{% trans "any information about this computer from OctoMon's database." %}
{% trans "Make sure you have deleted the client from fuss-server's octofussd database" %}
{% trans "otherwise octomon-sender will keep sending it to the central server." %}
<br><br>
<form action="" method="POST">
	{% csrf_token %}
<button type="submit" class="btn btn-lg btn-danger">
	<i class="fa fa-trash-o" aria-hidden="true"></i> {% trans 'Delete (fully remove from OctoMon database)' %}
</button>
</form>

{% endblock %}

hosts/templates/hosts/host.html
{% extends "base.html" %}
{% load i18n static %}


{% block title %}{% trans "Show" %} {{host.hostname}} ({{host.school.name}}){% endblock title %}

{% block head_resources %}
<link href="{{STATIC_URL}}css/jquery-ui.css" rel="stylesheet"/>
<script src="{{STATIC_URL}}js/jquery-ui.min.js"></script>
<script src="{{STATIC_URL}}js/scrapbooks.js"></script>

<script type="text/javascript">
  $(function() {
    $("#id_warranty_expire").datepicker({
      dateFormat: "yy-mm-dd",
    });
  });
</script>
{% endblock head_resources %}

{% block content %}
  <h1><a href="{% url 'school_detail' pk=host.school.pk %}">{{host.school}}</a> → {{host.hostname}}
	  {% if host.dismissed %}({% trans "dismissed" %}){% endif %}
  </h1>

    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#tabs-1">{% trans "Information" %}</a></li>
      {% if perms.hosts.change_computer %}
      <li><a data-toggle="tab" href="#tabs-2">{% trans "Edit" %}</a></li>
      {% endif %}
      <li><a data-toggle="tab" href="#tabs-3">{% trans "History" %}</a></li>
      <li><a data-toggle="tab" href="#tabs-4">{% trans "Alarms" %}</a></li>
      <li><a data-toggle="tab" href="#tabs-5">{% trans "ScrapBook" %}</a></li>
    </ul>
    <div class="tab-content">
    {# Information #}
    <br>
    <div id="tabs-1" class="tab-pane active"><div class="row"><div class="col-lg-2">
      <p>
        <em>{% trans 'Location:' %}</em>
        {% if host.location %}
          {{host.location}}
        {% else %}
          {% trans 'MISSING' %}
        {% endif %}
      </p></div>
      <div class="col-lg-2"><p>
        <em>{% trans 'Serial number:' %}</em>
        {% if host.serial_number %}
          {{host.serial_number}}
        {% else %}
          {% trans 'MISSING' %}
        {% endif %}
      </p></div>
      <div class="col-lg-2"><p>
        <em>{% trans 'Video serial number:' %}</em>
        {% if host.video_serial_number %}
          {{host.video_serial_number}}
        {% else %}
          {% trans 'MISSING' %}
        {% endif %}
      </p></div>
      <div class="col-lg-2"><p>
        <em>{% trans 'Warranty expires:' %}</em>
        {% if host.warranty_expire %}
          {{host.warranty_expire}}
        {% else %}
          {% trans 'MISSING' %}
        {% endif %}
      </p></div>
      <div class="col-lg-2"></div>
      <div class="col-lg-2"><p>
        {% if perms.problems.add_ticket or user.is_superuser %}
          <a href="{% url 'open_ticket_for_computer' id=host.id %}" class="btn btn-sn btn-danger btn-block">
            <span class="fa fa-bug"></span>
		        {% trans 'Report a problem' %}
          </a>
        {% endif %}
      </p></div></div>
      <br>
      {# New rendering #}
      <h4>{% trans "Main informations about this computer" %}</h4>
      <br>
      <div class="row">
	      <div class="col-lg-3 text-center">
		      <span class="fa fa-desktop fa-4x"></span>
	      </div>
	      <div class="col-lg-9">
		      <h3 style="font-weight:bold;">
			      {% trans "Hardware" %}
		      </h3>
          <b>{% trans "Producer" %}:</b> {{lc_system_vendor.value}}<br>
          <b>{% trans "Model" %}:</b> {{lc_system_product.value}}<br>
          <b>{% trans "Serial number" %}:</b> {{lc_serial_serial.value}}<br>
		      <b>{% trans "Chassis type" %}:</b> {{lc_chassis_type.value}}<br>
		      <b>{% trans "CPU type" %}:</b> {{lc_cputype.value}}<br>
		      <b>{% trans "CPU speed" %}:</b> {{lc_cpuspeed.value}} MHz<br>
		      <b>{% trans "RAM" %}:</b> {{lc_totalram.value}}<br>
	      </div>
      </div>
      <br>
      <div class="row">
	      <div class="col-lg-3 text-center">
		      <img src="{% static 'img/hard_disk.png' %}" style="max-width:90px;">
	      </div>
	      <div class="col-lg-9">
		      <h3 style="font-weight:bold;">
			      {% trans "Disks" %}
		      </h3>
		      <table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>{% trans "Device" %}</th>
					<th>{% trans "Mounted on" %}</th>
					<th>{% trans "Total space" %}</th>
					<th>{% trans "Space used" %}</th>
          <th>{% trans "Filesystem" %}</th>
				</tr>
			</thead>
			<tbody>
				{% for disk in disks %}
				<tr>
					<td>{{disk.0}}</td>
					<td>{{disk.1}}</td>
					<td>{{disk.2}}</td>
					<td>{{disk.3}}</td>
          <td>{{disk.4}}</td>
				</tr>
				{% endfor %}
			</tbody>
		      </table>
	      </div>
      </div>
      <br>
      <div class="row">
	      <div class="col-lg-3 text-center">
		      <img src="{% static 'img/packages.png' %}" style="max-width:90px;">
	      </div>
	      <div class="col-lg-9">
		      <h3 style="font-weight:bold;">
			      {% trans "Packages" %}
		      </h3>
		      <b>{{lc_ninstalledpackages.value}}</b> {% trans "installed packages" %}
		      <br><br>
		      {% for p in versions %}<b>
		      {% if p.name == "fussclient" %}fuss-client
		      {% else %}{{p.name}}{% endif %}</b> {% trans "version" %}
		      <b>{{ p.value }}</b><br>
		      {% endfor %}
	      </div>
      </div>
      <br>
      <div class="row">
	      <div class="col-lg-3 text-center">
          {% if host.is_server %}
		      <img src="{% static 'img/server.png' %}" style="max-width:90px;">
          {% else %}
          <img src="{% static 'img/client.png' %}" style="max-width:90px;">
          {% endif %}
	      </div>
	      <div class="col-lg-9">
          {% if host.is_server %}
		      <h3 style="font-weight:bold;">
			      {% trans "Server" %}
		      </h3>
		      <b>{% trans "Is a FUSS Server" %}:</b> {% trans "yes" %}
		      <br>
		      <b>{% trans "Has Captive portal configured" %}:</b>
		      {% trans lc_has_captive_portal.value %}<br>
		      <b>{% trans "Users" %}:</b> {{lc_total_users.value}}<br>
		      <b>{% trans "Uptime" %}:</b> {{lc_uptime.value}}
		      ({% trans "referred to the last data upload" %})
		      <br>
		      <b>{% trans "Remote administration address" %}:</b>
		      {{lc_tgu_domain.value}}
		      <br><br>
          {% else %}
          <h3 style="font-weight:bold;">
			      {% trans "Client" %}
		      </h3>
          {% endif %}
		      <h3 style="font-weight:bold;">
			      {% trans "Network" %}
		      </h3>
		      <table class="table table-striped table-bordered">
			         <thead>
				             <tr>
					              <th>{% trans "Interface" %}</th>
					              <th>{% trans "IP Address" %}</th>
					              <th>{% trans "MAC Address" %}</th>
				             </tr>
			         </thead>
			         <tbody>
			              {% if lc_external_ip_address %}
			              <tr><td>{% trans "External (WAN)" %} - {{lc_external_iface.value}}</td>
				            <td>{{lc_external_ip_address.value}}</td>
					    <td>{{lc_wan_mac}}</td></tr>
			              {% endif %}
				            {% for iface in interfaces %}
				                <tr>
					                 <td>{{iface.0}}</td>
					                 <td>{{iface.1}}</td>
					                 <td>{{iface.2}}</td>
				                </tr>
				            {% endfor %}
			         </tbody>
		      </table>
          {% if host.is_server %}
          <h3 style="font-weight:bold;">
			      {% trans "Latest /etc modifications" %}
		      </h3>
          {% if not etc %}{% trans "No etc data available." %}
          {% else %}
          <table class="table table-striped table-bordered">
			         <thead>
				             <tr>
					              <th>{% trans "Commit" %}</th>
					              <th>{% trans "Modifications" %}</th>
				             </tr>
			         </thead>
			         <tbody>
				            {% for commit in etc %}
				                <tr>
					                 <td><b>{{commit.message|linebreaksbr}}</b><br>{{commit.datetime}}</td>
					                 <td>
                             {% for file in commit.additions %}
                             <i class="fa fa-plus" style="color:green;"></i>
                             {{file}}<br>
                             {% endfor %}
                             {% for file in commit.deletions %}
                             <i class="fa fa-minus-circle" style="color:red;"></i>
                             {{file}}<br>
                             {% endfor %}
                           </td>
					                 <td>{{iface.2}}</td>
				                </tr>
				            {% endfor %}
			         </tbody>
		      </table>
          {% endif %}
          {% endif %}
	      </div>
      </div>
      <br>

      <h4>{% trans 'RAW recived data' %}</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>{% trans 'Component' %}</th>
            <th>{% trans 'Value' %}</th>
            <th>{% trans 'Logged on' %}</th>
          </tr>
        </thead>
        <tbody>
          {% for component in host.get_last_components %}
          <tr>
            <td>{{component.name}}</td>
            <td class="monospaced">
              <textarea disabled="disabled" style="width:100%;">{{component.value}}</textarea>
            </td>
            <td>{{component.timestamp|date:"Y-m-d H:i:s"}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% if perms.hosts.change_computer %}
      <p>
        {% if host.dismissed %}
          <a class="btn btn-lg btn-warning" href="{% url 'reinstate_host' id=host.id %}" onclick="if (!confirm('Are you sure?')) return false;">
            {% trans 'Reinstate' %}
          </a>
        {% else %}
          <a class="btn btn-lg btn-warning" href="{% url 'dismiss_host' id=host.id %}" onclick="return confirm('{% trans 'Are you sure?' %'}')">
		  <i class="fa fa-suitcase" aria-hidden="true"></i> {% trans 'Dismiss' %}
          </a>
        {% endif %}
        <a class="btn btn-lg btn-danger" href="{% url 'drop_host' pk=host.id %}" onclick="return confirm('{% trans 'Are you sure?' %'}')">
		<i class="fa fa-trash-o" aria-hidden="true"></i> {% trans 'Delete (fully remove from OctoMon database)' %}
        </a>
      </p>
      {% endif %}
    </div>

    {# Edit #}
    <div id="tabs-2" class="tab-pane">
      <div class="span5">
        <form method="POST" action="{{request.get_full_path}}">{% csrf_token %}
          <table class="table table-striped">
            {{edit_host_form.as_table}}
          </table>
          <input class="btn btn-lg btn-primary" type="submit" name="submit_edit_host" value="{% trans 'Submit Query' %}"/>
        </form>
      </div>
    </div>

    {# History #}
    <div id="tabs-3" class="tab-pane">HISTORY</div>

    {# Alarms #}
    <div id="tabs-4" class="tab-pane">
      {% include "problems/alarms.html" with acked_alarms=host.get_acked_alarms %}
    </div>

    {# ScrapBook #}
    <div id="tabs-5" class="tab-pane">
      {% include "schools/scrapbook.html" with scrapbooks=host.scrapbooks.all %}
    </div>
  </div>

{% endblock content %}