hosts/urls.py
from django.conf.urls import patterns, url
from hosts import views

urlpatterns = patterns('',
    url(r'^host/(?P<id>[0-9]+)$', 'hosts.views.host', name="host"),
    url(r'^dismiss/(?P<id>[0-9]+)$', 'hosts.views.dismiss_host', name="dismiss_host"),
    url(r'^reinstate/(?P<id>[0-9]+)$', 'hosts.views.reinstate_host', name="reinstate_host"),
    url(r'^create/$', 'hosts.views.create_host', name="create_host"),
    # The id in add_scrapbook url is the HOST id
    url(r'^add_scrapbook/(?P<id>[0-9]+)$', 'hosts.views.add_scrapbook', name="add_host_scrapbook"),
    url(r'^host/(?P<pk>[0-9]+)/drop$', views.DropHost.as_view(), name="drop_host"),
)

octomon/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from . import views as v

urlpatterns = patterns('',
    url(r'^$', 'octomon.views.home', name="home"),
    url(r'^login/$', 'octomon.views.octomon_login', name="login"),
    url(r'^logout/$', 'octomon.views.octomon_logout', name="logout"),
    url(r'^locationmap/$', v.LocationMap.as_view(), name="locationmap"),
    url(r'^user/(?P<id>[0-9]+)$', 'octomon.views.review_user', name="review_user"),
    url(r'^schools/', include('schools.urls')),
    url(r'^hosts/', include('hosts.urls')),
    url(r'^upload/', include('upload.urls')),
    url(r'^problems/', include('problems.urls')),
    url(r'^statistics/', include('stats.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
)

schools/urls.py
from django.conf.urls import patterns, url
from . import views as v

urlpatterns = patterns('',
    url(r'^areas/$', v.AreaList.as_view(), name="areas"),
    url(r'^area/(?P<id>[0-9]+)?$', 'schools.views.area', name="area"),
    url(r'^list/$', v.SchoolList.as_view(), name="schools"),
    url(r'^detail/(?P<pk>[0-9]+)?$', v.SchoolDetail.as_view(), name="school_detail"),
    url(r'^create/$', v.SchoolCreate.as_view(), name="school_create"),
    url(r'^update/(?P<pk>[0-9]+)$', v.SchoolUpdate.as_view(), name="school_update"),
    url(r'^delete/(?P<id>[0-9]+)$', 'schools.views.delete_school', name="delete_school"),
    url(r'^pdf_report/(?P<id>[0-9]+)$', 'schools.views.pdf_report', name="pdf_report_school"),
    url(r'^pdf_activity_report/(?P<id>[0-9]+)$', 'schools.views.pdf_activity_report', name="pdf_activity_report_school"),
    url(r'^csv_activity_report/(?P<id>[0-9]+)$', 'schools.views.csv_activity_report', name="csv_activity_report_school"),
    # The id in add_activity url is the SCHOOL id (we want to add a new
    # activity to xyz school)
    url(r'^add_activity/(?P<id>[0-9]+)$', 'schools.views.add_activity', name="add_activity"),
    # The id in edit_activity url is the ACTIVITY id (we want to modify the xyz
    # activity instance)
    url(r'^edit_activity/(?P<id>[0-9]+)$', 'schools.views.edit_activity', name="edit_activity"),
    url(r'^drop_other_hardware/(?P<pk>[0-9]+)$', v.DropOtherHardware.as_view(), name='drop_other_hardware'),
    # The id in add_scrapbook url is the SCHOOL id
    url(r'^add_scrapbook/(?P<id>[0-9]+)$', 'schools.views.add_scrapbook', name="add_school_scrapbook"),
    url(r'^create_other_hardware/(?P<id>[0-9]+)$', 'schools.views.create_other_hardware', name="create_other_hardware"),
    url(r'^edit_other_hardware/(?P<hw>[0-9]+)$', 'schools.views.edit_other_hardware', name="edit_other_hardware"),
    url(r'^computers/dismissed/(?P<id>[0-9]+)?$', 'schools.views.computers_dismissed', name="computers_dismissed"),
    url(r'^get_schools_activities_json/(?P<id>[0-9]+)?$', 'schools.views.get_schools_activities_json', name="get_schools_activities_json"),
    url(r'^search_activities/$', 'schools.views.search_activities', name="search_activities"),
    url(r'^log/$', 'schools.views.school_log', name="school_log"),
)

problems/models.py
# coding: utf-8
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Alarm(models.Model):
    host = models.ForeignKey('hosts.Computer', related_name='alarms')
    definition = models.ForeignKey('AlarmDefinition', related_name='alarms', blank=True)
    description = models.CharField(max_length=200)
    timestamp = models.DateTimeField(default=datetime.now, null=True, blank=True)
    ack = models.BooleanField(default=False)
    ack_by = models.ForeignKey(User, related_name='acked_alarms', null=True, blank=True)
    ack_when = models.DateTimeField(default=None, null=True, blank=True)

    def __str__(self):
        return "%s %s %s" %(self.description, _("on"), self.host)

    class Meta:
        db_table = 'alarms'


@python_2_unicode_compatible
class AlarmDefinition(models.Model):
    user = models.ForeignKey(User, related_name='alarm_definitions')
    description = models.CharField(max_length=200)
    code = models.TextField(help_text=_("c is a Computer object"))
    active = models.BooleanField(default=False)
    local = models.BooleanField(default=True)

    def __str__(self):
        return self.description

    class Meta:
        db_table = 'alarm_definition'


@python_2_unicode_compatible
class AlarmDefinitionRun(models.Model):
    school = models.ForeignKey('schools.School', related_name='alarm_definition_runs')
    definition = models.ForeignKey('AlarmDefinition', related_name='runs')
    school_timestamp = models.FloatField(default=0, null=True, blank=True)

    def __str__(self):
        return "%s %s %s" %(self.definition, _("execution on"), self.school)

    class Meta:
        db_table = 'alarm_definition_run'


@python_2_unicode_compatible
class Ticket(models.Model):
    opened = models.DateTimeField(null=True, blank=True)
    opened_by = models.ForeignKey(User, related_name='tickets_opened')
    ticket_for = models.CharField(max_length=200, blank=True)
    object_id = models.IntegerField(null=True, blank=True)
    description = models.CharField(max_length=2000,
        verbose_name=_('Problem description'))
    closed = models.DateTimeField(default=None, null=True, blank=True)
    closed_by = models.ForeignKey(User, related_name='tickets_closed', null=True, blank=True)

    def __str__(self):
        return self.ticket_for

    class Meta:
        db_table = 'ticket'
        ordering = ('-closed', '-opened', )

    def get_duration(self):
        if self.closed:
            return self.closed - self.opened
        else:
            return 0

    @property
    def is_open(self):
        return False if self.closed else True

    @property
    def is_closed(self):
        return True if self.closed else False


@python_2_unicode_compatible
class TicketNote(models.Model):
    ticket = models.ForeignKey('Ticket', related_name='notes', null=True, blank=True)
    user = models.ForeignKey(User, related_name='ticket_notes')
    timestamp = models.DateTimeField(null=True, blank=True)
    content = models.CharField(max_length=2000, blank=True)

    def __str__(self):
        return "%s %s" %(self.ticket, _("comment"))

    class Meta:
        db_table = 'ticket_note'

schools/models.py
# coding: utf-8
from datetime import datetime
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from stats.const import components_stats_to_be_kept


# this object is to create groups of school
# in italy they're called "Istituto Comprensivo"
# which manages more than one school, usually small ones.
class Area(models.Model):
    code = models.CharField(max_length=50, blank=True, verbose_name=_("code"))
    name = models.CharField(max_length=150, blank=True, verbose_name=_("name"))

    class Meta:
        db_table = 'area'
        ordering = ('name', )

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.code)

class SchoolManager(models.Manager):
    def get_queryset(self):
        return super(SchoolManager, self).get_queryset().filter(dismissed=False)

class AllSchoolManager(models.Manager):
    def get_queryset(self):
        return super(AllSchoolManager, self).get_queryset()

# this object represent a LAN
# but having also other attributes regarding building locations
# and so, we call it a "school"
class School(models.Model):

    objects = SchoolManager()
    all_objects = AllSchoolManager()

    name = models.CharField(max_length=200, unique=True,
                            blank=False, verbose_name=_("School name"))
    area = models.ForeignKey("Area", related_name="schools",
                             null=True, blank=True, #cascade=False, notNull=False
        verbose_name=_('Group'))
    address = models.CharField(max_length=300, blank=True)
    phone_number = models.CharField(max_length=200, blank=True)
    # TODO: EmailField?
    email_address = models.CharField(max_length=200, blank=True)
    lat = models.FloatField(null=True, blank=True,
        verbose_name=_('Latitude'))
    lon = models.FloatField(null=True, blank=True,
        verbose_name=_('Longitude'))
    last_timestamp = models.FloatField(default=0.0, null=True, blank=True)
    managed = models.ManyToManyField(User, related_name='schools', through='SchoolsManagers')
    dismissed = models.BooleanField(default=False)
    lasis_code = models.CharField(max_length=16, null=True, blank=True,
                                  verbose_name=_("LASIS School code"))

    class Meta:
        db_table = 'school'
        ordering = ('name', )

    def get_absolute_url(self):
        return reverse('school_detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        return "%s" % self.name

    def get_all_alarms(self):
        alarms = []
        for computer in self.computers.all():
            alarms.extend(computer.get_all_alarms())
        return alarms

    def get_acked_alarms(self):
        alarms = []
        for computer in self.computers.all():
            alarms.extend(computer.get_acked_alarms())
        return alarms

    def get_non_acked_alarms(self):
        alarms = []
        for computer in self.computers.all():
            alarms.extend(computer.get_non_acked_alarms())
        return alarms

    def get_last_state(self):
        if self.get_non_acked_alarms():
            return "PROBLEMS"
        else:
            return "OK"

    def get_last_timestamp(self):
        if self.last_timestamp:
            return datetime.fromtimestamp(self.last_timestamp)

    def has_server(self):
        server = self.computers.filter(hostname__istartswith=":SERVER:")
        return len(server) and server[0] or None

    def get_server(self):
        server = self.computers.filter(hostname__istartswith=":SERVER:")
        if len(server) == 1:
            return server[0]
        else:
            return None

    def get_computers(self):
        return self.computers.exclude(hostname__istartswith=":SERVER:")

    def get_active_computers(self):
        return self.computers.exclude(dismissed=True)

    def count_computers(self):
        computers = self.get_computers()
        return computers.count()

    def count_active_computers(self):
        computers = self.get_active_computers()
        return computers.count()

    def get_total_activity_hours(self):
        hours = 0.0
        for activity in self.activities.all():
            delta = activity.end_timestamp - activity.timestamp
            hours += (delta.seconds / 3600.0)
        return int(hours)

    def activity_log(self, first=None, limit=30, startDate=None, endDate=None):
        return Activity.objects.filter(school=self,
                                      timestamp__gte=startDate,
                                      timestamp__lt=endDate)

    def get_total_users(self):
        props = self.props.filter(propname='total_users')
        if len(props) > 0:
            return int(props[0].propvalue)
        else:
            return 0

    def get_other_hardware_all(self):
        return self.other_hardwares.all()

    def get_other_hardware_dismissed(self):
        return self.other_hardwares.filter(dismissed=True)

    def get_other_hardware_in_school(self):
        return self.other_hardwares.filter(dismissed=False)

    def get_daily_uses(self):
        data = {}
        for computer in self.get_computers():
            computer_daily_uses = computer.get_daily_uses()
            for key in computer_daily_uses:
                try:
                    data[key] += computer_daily_uses[key]
                except:
                    data[key] = computer_daily_uses[key]
        return data

    def count_daily_computers_used(self):
        data = {}
        for computer in self.get_computers():
            computer_days = computer.get_days_of_use()
            for key in computer_days:
                try:
                    data[key] += computer_days[key]
                except:
                    data[key] = computer_days[key]
        return data

    def get_components_stats(self):
        import re
        def _round_to_hundreds(val):
            """
            Rounds to the nearest hundreds
            """
            value = val
            print(value, type(value))
            if type(value) == type(""):
                if " " in value:
                    value = float(value.split(" ")[0])

            return int(round(value / 100.0) * 100)

        school_stats = {}
        for x in components_stats_to_be_kept:
            school_stats[x] = dict()
        for computer in self.computers.filter(dismissed__exact=False):
            for component in computer.get_last_components():
                if component.name in components_stats_to_be_kept:
                    name = component.name
                    if name == 'cpuspeed':
                        # Keep only numbers and decimal points. If there is one
                        # or more '.', split over '.' and keep the first part.
                        # Parse to int and round to hundreds
                        component.value = re.sub("[^0-9\.]", "", component.value)
                        if re.match('.', component.value):
                            component.value = component.value.split('.')[0]
                        try:
                            component.value = "%d" % _round_to_hundreds(int(component.value))
                        except:
                            pass
                    if name == 'cputype':
                        # Clean, and remove unnecessary whitespace
                        component.value = re.sub("^.*model name.*:\s", "", component.value)
                        component.value = re.sub("  +", " ", component.value)
                    if name == 'totalram':
                        # Round to hundreds
                        component.value = component.value
                    value = component.value.strip()
                    actual_count = int(school_stats.get(name).get(value, 0))
                    school_stats[name][value] = actual_count + 1
        return school_stats

class SchoolsManagers(models.Model):
    school = models.ForeignKey('School')
    manager = models.ForeignKey(User)

    class Meta:
        verbose_name_plural = 'Schools Managers'


class SchoolProp(models.Model):
    school = models.ForeignKey('School', related_name='props')
    propname = models.CharField(max_length=200)
    propvalue = models.CharField(max_length=200)

    class Meta:
        db_table = 'school_props'
        ordering = ('school', 'propname', )

    def __unicode__(self):
        return "%s - %s" % (self.school.name, self.propname)


class SchoolKey(models.Model):
    school = models.ForeignKey('School', related_name='keys')
    fingerprint = models.CharField(max_length=200, unique=True)
    crypto_key = models.TextField(blank=True)

    class Meta:
        db_table = 'school_key'
        ordering = ('school', '-pk', 'fingerprint', )

    # Using self.school (and School.__unicode__() return self.name) gives
    # DjangoUnicodeDecodeError, using self.school.name here fixes the problem
    def __unicode__(self):
        return "%s - %s" % (self.school.name, self.fingerprint)


class SchoolKeyUsage(models.Model):
    school = models.ForeignKey('School')
    key = models.ForeignKey('SchoolKey', related_name='usages', null=True, blank=True)
    timestamp = models.DateTimeField(default=datetime.now, null=True, blank=True)
    first_data_timestamp = models.FloatField(null=True, blank=True)
    last_data_timestamp = models.FloatField(null=True, blank=True)

    class Meta:
        db_table = 'school_key_usage'
        ordering = ('key', 'timestamp', )

    def get_first_timestamp(self):
        return datetime.fromtimestamp(self.first_data_timestamp)

    def get_last_timestamp(self):
        return datetime.fromtimestamp(self.last_data_timestamp)

    def print_timestamps(self):
        return "%s - (from %s to %s)" % (self.timestamp, self.get_first_timestamp(), self.get_last_timestamp())

    # Use explicit fields to avoid DjangoUnicodeDecodeError when leaving
    # models' __unicode__() methods do the job, just like in

schools/templates/schools/area.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Area" %}{% endblock title %}

{% block content %}
<h1>Area: {{area}}</h1>
<h3>{% trans "School in this area" %}:</h3>
<table class="table table-striped">
  <tr>
    <th>{% trans "School" %}</th>
    <th>{% trans "Address" %}</th>
  </tr>
  {% for school in area.schools.all %}
  <tr>
    <td><a href="{% url 'school_detail' pk=school.pk %}">{{school}}</a></td>
    <td>{{school.address}}</td>
  </tr>
  {% endfor %}
</table>
{% endblock content %}

schools/templates/schools/areas.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block title %}{% trans "Areas" %}{% endblock title %}


{% block content %}
<h1>{% trans "Available areas" %}</h1>
<script type="text/javascript">
$(function() {
  var area_table = $("#area_table").DataTable({
  language: {
  url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
  }
});
});
</script>
<table id="area_table" class="table table-striped">
  <thead>
    <tr>
      <th>{% trans "Area" %}</th>
      <th>{% trans "School" %}</th>
      <th>{% trans "Address" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for area in object_list %}
    {% for school in area.schools.all %}
    <tr>
      <td><a href="{% url 'area' id=area.id %}">{{area}}</a></td>
      <td><a href="{% url 'school_detail' pk=school.pk %}">{{school}}</a></td>
      <td>{{school.address}}</td>
    </tr>
    {% endfor %}
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

schools/templates/schools/computers_dismissed.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Dismissed computers" %}{% endblock title %}

{% block content %}
<h1>{% trans "Dismissed computers" %}</h1>
<table class="table table-striped">
  {% for computer in dismissed_computers %}
  <tr>
    <td>{{forloop.counter}}. <a
                                {% if computer.has_problems %}
                                class="problems-dismissed-computer"
                                {% endif %}
                                href="{% url 'host' id=computer.id %}">{{computer.hostname}}</a></td>
  </tr>
  {% endfor %}
</table>
<a href="{% url 'schools' %}">{% trans "Back" %}</a>
{% endblock content %}

schools/templates/schools/drop_hardware.html
{% extends "base.html" %}{% load i18n %}

{% block content %}
<div class="jumbotron">
{% trans "Really delete" %} {{object}} ?

<form action="" method="POST">{% csrf_token %}
  <input type="submit" class="btn btn-lg btn-danger" value="{% trans 'Yes' %}">
</form>
</div>
{% endblock %}

schools/templates/schools/edit_activity.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Edit activity" %}{% endblock title %}

{% block head_resources %}
<link href="{% static "css/jquery-ui.css" %}" rel="stylesheet"/>
<script src="{% static "js/jquery-ui.min.js" %}"></script>
<script src="{% static "js/jquery-ui-timepicker-addon.js" %}"></script>
<script src="{% static "tinymce-4.0.2/tinymce.min.js" %}"></script>

<script type="text/javascript">
  $(function() {
    $("#id_timestamp").datetimepicker({
      dateFormat: "yy-mm-dd",
      timeFormat: "HH:mm:ss",
    });
    $("#id_end_timestamp").datetimepicker({
      dateFormat: "yy-mm-dd",
      timeFormat: "HH:mm:ss",
    });
  });

  tinymce.init({
    menubar: false,
    selector: "#id_description",
    "theme_modern_toolbar_location": "top",
    "theme_modern_toolbar_align": "center",
    "paste_auto_cleanup_on_paste": true,
    "language": "en",
    "paste_convert_headers_to_strong": false,
    "theme_modern_resizing": true,
    "theme_modern_statusbar_location": "bottom",
    "paste_strip_class_attributes": "all",
    "theme": "modern",
    "elements": "form_description",
    "mode": "exact",
    "paste_use_dialog": false,
    "extended_valid_elements": "a[href|target|name]"
  });
</script>
{% endblock head_resources %}

{% block content %}
<div class="span6">
  <h1>{% trans 'Edit activity' %}</h1>
  <form method="POST" action="{% url 'edit_activity' id=activity.id %}">{% csrf_token %}
    <table class="table table-striped">
      {{form.as_table}}
    </table>
    <button class="btn btn-primary" type="submit">
      <span class="fa fa-edit"></span>
      {% trans "Edit" %}
    </button>
  </form>
</div>
{% endblock content %}

schools/templates/schools/school_form.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}
{% if school %}
{% trans "Edit School" %}: {{school.name}}
{% else %}
{% trans "New School" %}
{% endif %}
{% endblock title %}

{% block head_resources %}
<link rel="stylesheet" href="{% static "css/leaflet.css" %}" />
<link rel="stylesheet" href="{% static "css/leaflet.label.css" %}" />
<script src="{% static "js/leaflet.js" %}"></script>
<script src="{% static "js/leaflet.label.js" %}"></script>
{% endblock %}

{% block content %}
<script type="text/javascript">
  $(function() {
  $("#id_area").select2();
  $("#id_managed").select2();
  });
</script>

<h1>
  {% if school %}
  {% trans "Edit school" %}: {{school}}
  {% else %}
  {% trans 'New school' %}
  {% endif %}
</h1>

<div class="row">
  <div class="col-md-6">
    <form method="POST" action="{{ request.get_full_path }}">{% csrf_token %}
      <table class="table table-striped">
        {{form.as_table}}
        <tr>
          <td colspan="2">
            <button type="submit" class="btn btn-primary">
              {% if object %}
              <span class="fa fa-edit"></span>
              {% trans "Save" %}
              {% else %}
              <span class="fa fa-plus"></span>
              {% trans "Create" %}
              {% endif %}
            </button>
          </td>
        </tr>
      </table>
    </form>
  </div>
  <div class="col-md-6">
    <div id="map" style="width: 100%; height: 500px;"></div>
    <script type="text/javascript">
  var map;
  var lat_field = $("#id_lat");
  var lon_field = $("#id_lon");
  var address_field = $("#id_address");
  var marker;
  function main() {
  var GeoIcon = L.Icon.extend({});
  if(!lat_field.val()) {
  var base_lat = 46.45299704748289;
  var base_lon = 11.337890625;
      map = L.map('map').setView([base_lat,base_lon], 12);
      marker = L.marker([base_lat,base_lon], { draggable: "true"})
    } else {
      map = L.map('map').setView([lat_field.val(), lon_field.val()], 15);
      marker = L.marker([lat_field.val(),lon_field.val()], { draggable: "true"})
    }
    marker.addTo(map);
    var tiles = L.tileLayer('//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 18,
      minZoom: 2,
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);
    function geocode_this(position) {
      console.log(position);
      $.ajax({ url: "//nominatim.openstreetmap.org/reverse",
        method: "GET",
        dataType: "json",
        data: { "format" : "json",
          "addressdetails": 0,
          "lat": position.lat,
          "lon": position.lng
        },
        success: function(data) {
          address_field.val(data.display_name);
        }
      });
    }
    function update_marker_position_from_form_latlon(geocode=true) {
      var lat = lat_field.val();
      var lon = lon_field.val();
      marker.setLatLng([lat, lon]);
      map.setView([lat, lon], 13);
      if(geocode) {
        geocode_this({lat: lat, lng: lon});
      }
    }

    lat_field.keyup(function() {
      update_marker_position_from_form_latlon();
    });

    lon_field.keyup(function() {
      update_marker_position_from_form_latlon();
    });

    function update_marker_position_from_address() {
      address = address_field.val()
      $.ajax({ url: "//nominatim.openstreetmap.org/search?q=abbiategrasso&format=json&addressdetails=1",
        method: "GET",
        dataType: "json",
        data: {"format": "json",
          "addressdetails": 0,
          "q": address },
        success: function(data) {
          if(data.length) {
            var my_lat = data[0].lat;
            var my_lon = data[0].lon;
            lat_field.val(my_lat);
            lon_field.val(my_lon);
            update_marker_position_from_form_latlon(geocode=false);
          }
        }
      });
    }

    address_field.keyup(function() {
      update_marker_position_from_address();
    });
    marker.on('dragend', function(event) {
      var position = marker.getLatLng();
      lat_field.val(position.lat);
      lon_field.val(position.lng);
      marker.setLatLng(position);
      map.setView(position);
      geocode_this(position);
    });
  }

  $(document).ready(main);
</script>

  </div>
</div>
{% endblock content %}

schools/templates/schools/schools.html
{% extends "base.html" %}
{% load i18n %}


{% block title %}{% trans "List" %}{% endblock title %}

{% block head_resources %}
<script type="text/javascript">
  $(function() {
    $("#schools-table").dataTable();
  });
</script>
{% endblock head_resources %}

{% block content %}
<div class="pull-right">
  {% if perms.schools.add_school %}
  <a class="btn btn-primary" href="{% url 'school_create' %}">
    <span class="fa fa-graduation-cap"></span>
    {% trans "Create new school" %}
  </a>
  {% endif %}
  {% if schools and perms.hosts.add_computer %}
    <a class="btn btn-primary" href="{% url 'create_host' %}">
      <span class="fa fa-plus"></span>
      {% trans "Add new computer" %}
    </a>
  {% endif %}
</div>
<h1>{% trans "Listing schools" %}</h1>
<table id="schools-table" class="table table-striped">
  <thead>
    <tr>
      <th>{% trans "Name" %}</th>
      <th>{% trans "Area" %}</th>
      <th>{% trans "Manager" %}</th>
      <th>{% trans "Address" %}</th>
      <th>{% trans "Phone number" %}</th>
      <th>{% trans "Email" %}</th>
      <th>{% trans "Status" %}</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for school in schools %}
    <tr>
      <td><a href="{% url 'school_detail' pk=school.pk %}">{{school.name}}</a></td>
      <td>
        {% if school.area %}
        <a href="{% url 'area' id=school.area.id %}">
          {{school.area}}
        </a>
        {% endif %}
      </td>
      <td>
        {% for m in school.managed.all %}
        <a href="{% url 'review_user' id=m.id %}">
          {% if m.first_name %}
          {{m.first_name}} {{m.last_name}}
          {% else %}
          {{m.username}}
          {% endif %}
        </a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
      </td>
      <td>{{school.address}}</td>
      <td>{{school.phone_number}}</td>
      <td><a href="mailto:{{school.email_address}}">{{school.email_address}}</a></td>
      <td>{#school.get_last_state#}</td>
      <td>
        <a class="btn btn-sm btn-info"
           href="{% url 'pdf_report_school' id=school.id %}">
          <span class="fa fa-print"></span>
          {% trans "Report" %}
        </a>
      </td>
      <td>
        {% if perms.schools.change_school %}
        <a class="btn btn-sm btn-danger" href="{% url 'school_update' pk=school.pk %}">
          <span class="fa fa-edit"></span>
          {% trans "Edit" %}
        </a>
        {% endif %}
      </td>
      <td>
        {% if perms.schools.delete_school %}
        <a class="btn btn-sm btn-danger"
           href="{% url 'delete_school' id=school.id %}" onclick="if (!confirm('Are you sure?')) return false;">
          <span class="fa fa-remove"></span>
          {% trans "Destroy" %}
        </a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br/> {# *ugly* quick workaround to avoid datatables enabled table and footer mess with each other #}
{% endblock content %}